apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-workloads-quota
  namespace: ai-workloads
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 500Gi
    limits.cpu: "200"
    limits.memory: 1000Gi
    persistentvolumeclaims: "50"
    pods: "200"
    requests.nvidia.com/gpu: "10"
